var stage,curentPage,g_iCurrentPage,m_pgObjCaller,KeyCode,folder_Resource="Resource",styteView="Nor",m_pointDown={},url=window.location.pathname,_global_lenSound=1E3;buzz.defaults.formats=["mp3"];buzz.defaults.preload="metadata";var m_soundPlaying=new buzz.sound("/Images/abc"),m_EndPos,m_StartPos,imageData=null;
function InitLacVietScript(){for(var a=stage.children,c=1;c<a.length;c++)a[c].hide(),a[c].draw();a[0].show();curentPage=a[0];g_iCurrentPage=0;window.addEventListener("keydown",doKeyDown,!0);window.addEventListener("keypress",doKeyPress,!0);a=window;window.history.forward();a.onload=void 0;curentPage.on("mousedown",MouseDown);FullScreen();var b=curentPage.getInitConfig();b.callback&&eval(b.callback);if("Nor"!=styteView)for(a=stage.children,c=1;c<a.length;c++)b=a[c].getInitConfig(),curentPage=a[c],
eval(b.callback);responsiveVoice.voiceSupport||alert("kh\u00f4ng h\u1ed7 tr\u1ee3 gi\u1ecdng \u0111\u1ecdc")}function doKeyPress(a){null!=m_pgObjCaller&&"Shape"===m_pgObjCaller.nodeType&&m_pgObjCaller.readonly&&(a=a.keycode||a.which,m_pgObjCaller.setText(m_pgObjCaller.getText()+String.fromCharCode(a)),InvalidateObj("",""));return!1}
function doKeyDown(a){KeyCode=a.keyCode?a.keyCode:a.which;if(8==KeyCode&&null!=m_pgObjCaller&&"Shape"===m_pgObjCaller.nodeType&&m_pgObjCaller.readonly){var c=m_pgObjCaller.getText(),c=c.substring(0,c.length-1);m_pgObjCaller.setText(c);InvalidateObj("","");event.stopPropagation();a.preventDefault();return!0}if(46==KeyCode||37==KeyCode||38==KeyCode||39==KeyCode||40==KeyCode)event.stopPropagation(),a.preventDefault();a=curentPage.getName()+"_OnKeyDown";if("function"===typeof window[a])window[a]()}
function MouseDown(a){m_pointDown.x=a.x;m_pointDown.y=a.y}var m_dZoomScale=1;function detectmob(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?!0:!1}
function FullScreen(){var a=document.getElementById("Doc").clientWidth,a=!1===detectmob()?70*a/100:98*a/100,c=screen.availHeight-95,a=a/stage.getWidth(),c=c/stage.getHeight();m_dZoomScale=Math.min(a,c);m_dZoomScale=a;stage.setSize(stage.getWidth()*m_dZoomScale,stage.getHeight()*m_dZoomScale);stage.setScale(m_dZoomScale);if("Nor"!=styteView)for(c=stage.children,a=0;a<c.length;a++)c[a].show(),c[a].draw();else InvalidateObj("","")}
function removeFlashMarkup(a,c){var b=document.getElementById(c);null!=b&&document.body.removeChild(b)}
function createFlashMarkup(a,c,b,e,f,k,g){g=document.createElement("embed");g.setAttribute("id",a);g.setAttribute("width",e*m_dZoomScale);g.setAttribute("height",f*m_dZoomScale);k.indexOf("/");g.setAttribute("src",folder_Resource+"/"+k);g.setAttribute("type","application/x-shockwave-flash");a="position: fixed; left: {0}px; top: {1}px; width: {2}px; height: {3}px;".format(c*m_dZoomScale,b*m_dZoomScale,e*m_dZoomScale,f*m_dZoomScale);g.setAttribute("style",a);document.body.appendChild(g)}
String.prototype.insert=function(a,c){return 0<a?this.substring(0,a)+c+this.substring(a,this.length):c+this};
function InitText(a,c,b,e,f,k,g,m,l,u,n,q,x,v,w,D,E,C,t,p,A,F,y,G,z,H,M,N,I,B,J,K,L){var h={};0==isNaN(a.substring(0,1))&&(a="_"+a);h.name=a;h.x=c;h.y=b;h.width=e;h.height=f;h.text=k;switch(G){case "0":h.fill=g;break;case "2":n=n.replace(/[*:?<>"|\/]/ig,"");if(0<n.indexOf("/")||""===n)break;n=folder_Resource+"/"+n;y=new Image;y.crossOrigin="anonymous";y.onload=function(){stage.draw()};y.onerror=function(){this.src=n.substring(0,n.lastIndexOf("."))+".PNG";this.onerror=function(){this.src=n.substring(0,
n.lastIndexOf("."))+".JPG";this.onerror=function(){this.src=n.substring(0,n.lastIndexOf("."))+".GIF";this.onerror=function(){Message("Image not found: "+n);h.fill=g}}}};a="repeat";0==z?a="center":2==z&&(a="stress");y.src=n;h.fill={image:y,offset:[0,0],repeat:a};break;case "3":z=h.height;z>h.width&&(z=h.width);h.fill={start:{x:h.width/2,y:h.height/2,radius:z/3},end:{x:h.width/2,y:h.height/2,radius:z},colorStops:[0,g,1,y]};break;case "4":h.fill={start:{x:h.width/2,y:0},end:{x:h.width/2,y:h.height},
colorStops:[.5,g,1,y]}}h.textFill=l;h.fontSize=80*q/100;h.fontFamily=x;h.fontStyle=v;h.align=w;0!=C&&(l=e/2,q=f/2,h.x=c+l,h.y=b+q,h.offset=[l,q],h.rotationDeg=C);h.stroke=F;0==A&&(A=1E-4);h.strokeWidth=A/2;h.textStroke=H;0==B&&(B=1E-4);h.textStrokeWidth=B;h.verticalAlign=D;h.shadow={color:L,blur:I,offset:[J,K],alpha:.5};switch(E){case 0:t==p&&(p=t=0);h.shapeType="Rect";h.sides=t;h.sidesY=p;break;case 1:t==p&&(p=t=0);h.shapeType="Ellipse";h.sides=t;0>=p&&(p=360);h.sidesY=p;break;case 2:t==p&&(p=t=
0);h.shapeType="Circle";h.sides=t;0>=p&&(p=360);h.sidesY=p;break;case 3:h.shapeType="RoundRect";h.cornerRadius=45*t/100;break;case 4:h.shapeType="Triangula";h.sides=t;0>p&&(p=0);h.sidesY=p;break;case 5:h.shapeType="Lozenge";break;case 6:h.shapeType="Parallelogram";h.sides=t;break;case 7:h.shapeType="Trapezium";h.sides=t;h.sidesY=p;break;case 8:h.shapeType="Pentagon";h.sides=5;h.sides=t;h.sidesY=p;break;case 9:h.shapeType="RegularPolygon";h.sides=8;r=e/2;r>f/2&&(r=f/2);h.radius=r;break;case 10:h.shapeType=
"RegularPolygon";h.sides=6;r=e/2;r>f/2&&(r=f/2);h.radius=r;break;case 11:h.shapeType="altp",h.sides=t,r=e/2,r>f/2&&(r=f/2),h.radius=r}return h}function wrapText(a,c,b,e,f,k){c=c.split(" ");for(var g="",m=0;m<c.length;m++){var l=g+c[m]+" ";a.measureText(l).width>f?(a.fillText(g,b,e),g=c[m]+" ",e+=k):g=l}a.fillText(g,b,e)}
function drawEllipse(a,c,b,e,f,k,g){ox=e/2*1;oy=f/2*1;xe=c+e;ye=b+f;xm=c+e/2;ym=b+f/2;c=k*Math.PI/180;g=g*Math.PI/180;b=Math.min(ox,oy);ox!==oy&&(scaleX=ox/b,scaleY=oy/b,a.translate(xm,ym),a.scale(scaleX,scaleY));a.arc(0,0,b,c,g,!0)}window.requestAnimFrame=function(a){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
function FindShape(a,c){var b=null;if(""===a)null!=m_pgObjCaller&&(curentPage=m_pgObjCaller.parent,"Layer"!=curentPage.nodeType&&(curentPage=curentPage.parent)),b=curentPage;else for(var e=stage.children,f=0;f<e.length;f++)if(e[f].getName()==a){b=e[f];break}if("undefined"==typeof c||""===c)return m_pgObjCaller;if(null!=b)for(0==isNaN(leftStr(c,1))&&(c="_"+c),c=c.toString(),b=b.children,f=0;f<b.length;f++){if(b[f].getName().toLowerCase()==c.toString().toLowerCase())return b[f];if("Group"==b[f].nodeType&&
b[f].children)for(j=0;j<b[f].children.length;j++)if(b[f].children[j].getName().toLowerCase()==c.toString().toLowerCase())return b[f].children[j]}return null}function FindPage(a){var c=null;if(""===a)c=curentPage;else if(null==c)for(var b=stage.children,e=0;e<b.length;e++)if(b[e].getName()==a){c=b[e];break}return c}function AddRsc(a,c,b){}var _hiddenInput=null;
function CreateHiddenInput(a){null==_hiddenInput&&(_hiddenInput=document.createElement("input"),_hiddenInput.type="text",_hiddenInput.style.position="fix",_hiddenInput.style.opacity=0,document.body.appendChild(_hiddenInput),_hiddenInput.addEventListener("keyup",function(a){m_pgObjCaller.setText(_hiddenInput.value);curentPage.draw()}));_hiddenInput.value=m_pgObjCaller.getText();_hiddenInput.focus()}
function AllowEditText(a,c,b){a=FindShape(a,c);if("undefined"===typeof b)return a.readonly;a.readonly=b}
function AnimationFly(a,c,b,e,f){a=FindShape(a,c);if(null!=a){c=a.getX();var k=a.getY();if(8>=f){switch(f){case 1:a.setX(0);a.setY(0);break;case 2:a.setY(0);break;case 3:a.setX(stage.getWidth());a.setY(0);break;case 4:a.setX(stage.getWidth());break;case 5:a.setX(stage.getWidth());a.setY(stage.getHeight());break;case 6:a.setY(stage.getHeight());break;case 7:a.setX(0);a.setY(stage.getHeight());break;case 8:a.setX(0)}f=Math.abs(c-a.getX());var g=Math.abs(k-a.getY());MoveObject(a,c,k,Math.sqrt(f*f+g*
g)/e*b)}}}function AnimationMagic(a,c,b,e,f,k,g){SetRsc(a,c,k)}function SetResize(a,c,b,e){if(null==FindShape(a,c))return""}function SetOpacity(a,c,b){a=FindShape(a,c);if(null==a)return"";a.setOpacity(b)}function AnimationPage(a,c,b,e,f){GoToPage(a)}function AutoRunAction(a,c){}function BeginRecordAction(){}function Brightness(a,c,b,e){}function Browse(a,c){}function BrowseFile(a){}function ClickToWord(a,c,b){}function CloseFile(){curentPage.hide();curentPage.draw()}function ChangeVoice(a){}
function CloseSocket(){}function Connect(a,c){}function CopyFile(a,c){}function CreateFolder(a){}function CreateNewPage(a){stage.add(new Kinetic.Layer({name:a}))}
function CreateObj(a,c,b,e,f,k,g,m){""==c&&(c=(new Date).getTime());b=new Kinetic.Text(InitText(c,f,k,g,m,e,"rgba(0, 0, 0, 0)","rgba(255, 255, 255, 1.00)","rgba(0, 0, 0, 1)","rgba(255, 255, 255, 1.00)",folder_Resource+"/",14,"Verdana","Normal","center","middle",0,"0.00","30","30",0,"rgba(255, 255, 255, 1)","rgba(0, 0, 0, 1)","0","0","rgba(255, 255, 255, 1)","0","0","4","0",0,0,"rgba(128, 128, 128, 1)"));FindPage(a).add(b);InvalidateObj();return c}function DanhVan(a){a.toLowerCase()}
function Delay(a,c){"undefined"!==typeof c&&setTimeout(a,c)}function DeleteObj(a,c){var b=FindPage(a);if(null!=b){var e=FindShape(a,c);null!=e&&(e.remove(),b.draw())}}function DestroyObjectHwnd(a,c){}function DivideImage(a,c,b,e,f){}function DocChu(a){a.toLowerCase()}function DrawPageInObject(a,c){}function DrawStyte(a,c,b){}function Enable(a,c,b){}function EnableWndDraw(a,c,b){}function EndRecordAction(){}function ExecAsThread(a){return eval(a.toString())}function ExeDML(a,c){}
function ExeQuery(a,c){}function ExitApp(a,c){window.close()}function ExportObj(a,c,b){}function StopVN(){}function FileFind(a,c){}function FillImage(a,c,b,e,f,k,g){if("undefined"===typeof k||"undefined"===typeof g)a=stage.getMousePosition(),k=a.x,g=a.y;PaintFillColor("",c,RGB(b,e,f));PaintDownObj(k,g,c,40)}function FindObj(a,c){var b=FindShape(a,c);return b?b.getName():""}
function GetBoundsText(a,c,b,e,f){a=FindShape(a,c);if(null==a)return null;c=a.getText();isNaN(e)||isNaN(f)||(c=c.substr(e,f));e=a.getBoundsText(c);b.toLowerCase();return""==b||"l"==b?e.actualBoundingBoxLeft:"t"==b?a.getY():"w"==b?e.width:"h"==b?2*a.getTextHeight():"r"==b?e.actualBoundingBoxRight:"b"==b?a.getY()+a.getTextHeight():0}function GetColCount(a,c){}
function GetColor(a,c,b){if(a=FindShape(a,c)){if(null==b||"undefined"==typeof b)return b=a.getFill(),"rgba(0, 0, 0, 0)"==b?0:b.start&&b.end?2:null!=b.image?b=b.image.src.substring(b.image.src.lastIndexOf("/")+1,b.image.src.lastIndexOf(".")):1;b=a.getFill();return null!=b.image?b=b.image.src.substring(b.image.src.lastIndexOf("/")+1,b.image.src.lastIndexOf(".")):"rgba(0, 0, 0, 0)"==b?"rgba(0, 0, 0, 0)":b.start&&b.end?b.colorStops:b}b=stage.getMousePosition();b=curentPage.getContext().getImageData(b.x,
b.y,1,1).data;if("undefined"!=b)return"rgba({0}, {1}, {2}, {3})".format(b[0],b[1],b[2],b[3])}function GetCountCall(a){}function GetCountObj(a,c){return FindPage(a).children.length}function GetCursorPos(a,c){var b=stage.getMousePosition();return null!=c||"undefined"!=picel?""===a||"x"===a?parseInt(b.x/m_dZoomScale):parseInt(b.y/m_dZoomScale):""===a||"x"===a?parseInt(b.x):parseInt(b.y)}function charCodeAt(a,c){return a.charCodeAt(c)}function GetFocusObj(){return m_pgObjCaller.getName()}
function GetFolder(a){}function GetHeight(a,c){var b=FindShape(a,c);return null==b?"":b.getHeight()}function GetKeyByID(a){return GetFolder()+"\\"+folder_Resource+"\\"+a+".PNG"}function GetKeyDown(a,c){return String.fromCharCode(KeyCode)}function GetLeft(a,c){var b=FindShape(a,c);if(null==b)return"";if("undefined"!=typeof b)return b.getX()}function GetMoveClick(a,c){return!1}function GetMoveView(a,c){return FindShape(a,c).getDraggable()}
function GetName(a,c){var b;b=null!=c?curentPage.children[c].getName():m_pgObjCaller.getName();return isNaN(b)?b:parseInt(b)}function GetNextFocus(){var a=m_pgObjCaller.index+1;a>=curentPage.children.length&&(a=0);return curentPage.children[a].getName()}function GetPointDown(a,c,b){return null!=b?""==b||"x"==b?m_pointDown.x:m_pointDown.y:m_pointDown.x}function GetPointDownEx(a,c){return""==a||"x"==a?m_pointDown.x:m_pointDown.y}
function GetPosSound(){return m_soundPlaying?m_soundPlaying.getTime():-1}function GetRectRestore(a,c,b){a=FindShape(a,c);if(null==a)return"";a=a.getInitConfig();return null!=b?""==b||"l"==b?a.x:"t"==b?a.y:"w"==b?comnfig.width:"h"==b?comnfig.height:"r"==b?a.x+comnfig.width:"b"==b?a.y+comnfig.height:0:a.x}function GetResize(a,c){return!1}
function GetRGB(a,c){"#"==c[0]&&(c=c.substr(1));if(3==c.length){var b=c;c="";for(var b=/^([a-f0-9])([a-f0-9])([a-f0-9])$/i.exec(b).slice(1),e=0;3>e;e++)c+=b[e]+b[e]}b=/^([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(c).slice(1);if("r"===a)return parseInt(b[0],16);if("g"===a)return parseInt(b[1],16);if("b"===a)return parseInt(b[2],16)}function GetRotateObj(a,c){return FindShape(a,c).getRotationDeg()}function GetRowCount(a,c){return 0}
function GetRsc(a,c){var b=FindShape(a,c);if(null==b)return"";var e=b.getRsc();if(""==e){b=b.getFill();if(null==typeof b.image||"undefined"==typeof b.image)return null;b=b.image.src;return null==typeof b||"undefined"==typeof b?null:b.substring(b.lastIndexOf("/")+1,b.lastIndexOf("."))}return e}
function EvenToText(a){var c="";a=parseInt(a);switch(a){case 0:c="mouseup";break;case 1:c="mousedown";break;case 2:c="OnKeyDown";break;case 3:c="OnLoadPage";break;case 4:c="OnTimer";break;case 5:c="dblclick";break;case 6:c="mouseover";break;case 7:c="dblclick";break;case 8:c="dblclick";break;case 10:c="mouseout";break;default:c=""}return c}
function GetScriptObj(a,c,b,e){if("undefined"!=typeof c){a=FindShape(a,c);if(null==a)return"";b=EvenToText(b);if(""!=b){a=a.eventListeners[b][0].handler.toString();c=a.indexOf("{");var f=a.lastIndexOf("}")+1;a=a.substring(c,f);c=new Function(a);"undefined"!=typeof m_pgObjCaller&&(m_pgObjCaller.off(b),m_pgObjCaller.on(b,c));"undefined"==typeof e&&(a=a.replace("m_pgObjCaller = this;",""),(new Function(a))())}}}
function SetScriptObj(a,c,b,e){a=FindShape(a,c);if(null==a)return"";e=EvenToText(e);c=b.indexOf("{");var f=b.lastIndexOf("}")+1;b=b.substring(c,f);b=b.insert(1,"m_pgObjCaller = this;\r\n");""!=e&&(m_pgObjCaller=a,b=new Function(b),a.off(e),a.on(e,b))}function GetSelectObj(){return m_pgObjCaller.getName()}function GetSelText(a,c){}function GetShowObject(a,c){var b=FindShape(a,c);return null==b?"":b.getAttrs().visible}
function GetText(a,c){var b=FindShape(a,c);if(null==b)return"-1";b=b.getText();return""==b||" "==b||isNaN(b)?b:parseInt(b)}function GetTextFromID(a,c){return"undefined"!=typeof hashIDText[a]?hashIDText[a]:""}function GetTop(a,c){var b=FindShape(a,c);if(null==b)return"";if("undefined"!=typeof b)return b.getY()}function GetTypeObj(a,c){return"Text"}function GetValueTable(a,c,b,e){}function GetVar(a){return myArray[a]}function GetVirtKey(a){a=!1;return a=KeyCode.ctrlKey}
function GetWidth(a,c){var b=FindShape(a,c);return null==b?"":b.getWidth()}function GoToPage(a){var c=null;if(""==a)c=curentPage;else{a=a.replace(/ /g,"_");for(var b=stage.children,e=0;e<b.length;e++)if(b[e].getName()==a){g_iCurrentPage=e;c=b[e];m_pgObjCaller=null;break}}null!=c&&(curentPage.hide(),curentPage.draw(),curentPage=c,a=curentPage.getInitConfig(),a.callback&&eval(a.callback),curentPage.show(),curentPage.draw())}function InitRandom(a){}function InsertPageFromFile(a,c){}
function intersectRectabcd1234(a,c){return a.left<=c.right&&c.left<=a.right&&a.top<=c.bottom&&c.top<=a.bottom}function IntersectRect(a,c,b,e){c=FindShape(a,c.toString());if(null==c)return!1;a=FindShape(a,b.toString());if(null==a)return!1;stage.getMousePosition();c.getX();c.getY();c.getX();c.getWidth();c.getY();c.getHeight();a.getX();a.getY();a.getX();a.getWidth();a.getY();a.getHeight()}
function InvalidateObj(a,c){if(""===a)if("undefined"===typeof m_pgObjCaller)curentPage&&curentPage.draw();else{if(null!=m_pgObjCaller)for(curentPage=m_pgObjCaller.parent;"Layer"!=curentPage.nodeType;)curentPage=curentPage.parent;curentPage.draw()}else{var b=FindPage(a);null!=b&&b.draw()}}function IsFileName(a){}function IsRsc(a){var c=FileFind(folder_Resource+"\\",a);""==c&&(c=FileFind(folder_Resource+"\\",a));return c}function KillTimerPage(){clearInterval(myVarTimerPage)}
function LengthSound(a,c){if("undefined"==typeof a)return m_soundPlaying.getDuration();var b=new buzz.sound(folder_Resource+"/"+a);b.addEventListener("canplaythrough",function(a){return b.getDuration()})}function Listent(a){}function MarkObj(a,c,b,e,f,k){}function Message(a,c,b){if(null!=c)return confirm(a)?6:7;alert(a)}
function transitionTo(a,c,b,e,f,k,g,m,l,u){a=FindShape(a,c);if(null==a)return"";c="linear";if("undefined"!=typeof l){var n="linear ease-in ease-out ease-in-out back-ease-in back-ease-out back-ease-in-out elastic-ease-in elastic-ease-out elastic-ease-in-out bounce-ease-out bounce-ease-in bounce-ease-in-out strong-ease-in strong-ease-out strong-ease-in-out".split(" ");0<=n.indexOf(l)?c=l:(l=parseInt(l),l<n.length&&(c=n[l]))}l=a.getInitConfig();-1==e&&(e=l.x);-1==f&&(f=l.y);b=parseInt(b)/1E3;l=1;"undefined"!=
typeof k&&(l=k);k=0;"undefined"!=typeof g&&(k=g*Math.PI/180);g=1;"undefined"!=typeof m&&(g=m);"undefined"!=typeof u?a.transitionTo({x:e,y:f,duration:b,easing:c,rotation:k,opacity:g,scale:{x:l,y:l},callback:function(){eval(u)}}):a.transitionTo({x:e,y:f,duration:b,rotation:k,easing:c,scale:{x:l,y:l},opacity:g})}
function MoveObjectTo(a,c,b,e,f,k,g,m){var l=null,l=""===c?m_pgObjCaller:FindShape(a,c);if(null!=l){var u="linear";if("undefined"!=typeof g){var n="linear ease-in ease-out ease-in-out back-ease-in back-ease-out back-ease-in-out elastic-ease-in elastic-ease-out elastic-ease-in-out bounce-ease-out bounce-ease-in bounce-ease-in-out strong-ease-in strong-ease-out strong-ease-in-out".split(" ");if(0<=n.indexOf(g))u=g;else{var q=parseInt(g);q<n.length&&(u=n[q])}}n=f*k/100;q=l.getInitConfig();-1==b&&(b=
q.x);-1==e&&(e=q.y);5>arguments.length?(l.setPosition(b,e),stage.draw()):"undefined"!=typeof m?l.transitionTo({x:b,y:e,duration:n,easing:u,callback:function(){eval(m)}}):l.transitionTo({x:b,y:e,duration:n,easing:u})}}function MoveObjectToEx(a,c,b,e,f,k,g,m,l,u){}function toHex(a){if(null==a||0==a)return"00";for(a=Number(a).toString(16);2>a.length;)a="0"+a;return a}function RGB(a,c,b,e){return"#"+toHex(a)+toHex(c)+toHex(b)}function NewFile(a){}
function NextPage(){var a=stage.children;g_iCurrentPage>=a.length-1||(curentPage.hide(),curentPage.draw(),g_iCurrentPage+=1,curentPage=a[g_iCurrentPage],m_pgObjCaller=null,a=curentPage.getInitConfig(),a.callback&&eval(a.callback),curentPage.show(),curentPage.draw())}function ObjFlip(a,c,b,e){}function OpenFile(a,c){a=replaceStr(a,"\\","");var b=a.replace(/lvm/g,"html"),e=window.location.pathname,e=e.substring(0,e.lastIndexOf("/")+1);window.open(e+b,"_self")}function OpenFileCHM(a){}
function OpenFileFromID(a){}function OpenUrl(a){window.open(a,"NewWindow","blah")}function OrderObj(a,c,b){a=FindShape(a,c);0==b?a.moveDown():1==b?a.moveToTop():2==b?a.moveUp():3==b&&a.moveToBottom()}function PaintCap(a,c,b){}function PaintColor(a,c,b,e){a=FindShape(a,c);null!=a&&(a=a.getContext(),"undefined"!=typeof e&&(b="#"==b[0]?"rgba({0}, {1}, {2}, {3})".format(GetRGB("r",b),GetRGB("g",b),GetRGB("b",b),e):b.replace(/[^,]+(?=\))/,e)),a.strokeStyle=b)}
function PaintFillColor(a,c,b){a=FindShape(a,c);null!=a&&(a.getContext().fillStyle=b)}String.prototype.format=function(){var a=this;for(arg in arguments)a=a.replace("{"+arg+"}",arguments[arg]);return a};function PaintColorA(a,c,b){a=FindShape(a,c);if(null!=a){a=a.getContext();if("undefined"==typeof b)return a.strokeStyle;b=a.strokeStyle;b="#"==b[0]?"rgba({0}, {1}, {2}, {3})".format(GetRGB("r",b),GetRGB("g",b),GetRGB("b",b),value_a):b.replace(/[^,]+(?=\))/,value_a);a.strokeStyle=b}}
var m_imagePaint=new Image;function PaintImage(a,c,b){if("undefined"!=typeof b||null!=b)b=b.toString(),b=b.replace(/[*:?<>"|\/]/ig,""),m_imagePaint.onload=function(){},m_imagePaint.onerror=function(){this.src=folder_Resource+"\\"+b+".JPG";this.onerror=function(){this.src=folder_Resource+"\\"+b+".GIF";this.onerror=function(){Message("Kh\u00f4ng tim th\u1ea5y id rsc: "+b)}}},m_imagePaint.crossOrigin="anonymous",m_imagePaint.src=folder_Resource+"\\"+b+".PNG"}function PaintImageS(a,c,b,e,f){}
function PaintPattern(a,c,b,e,f){}function PaintType(a,c,b){a=FindShape(a,c);if(null!=a){if("undefined"==typeof b)return a.paintType();a.paintType(b)}}function PaintWidth(a,c,b){a=FindShape(a,c);null!=a&&(a=a.getContext(),a.lineJoin="round",a.lineCap="round",a.lineWidth=b)}function PauseAudio(a){m_soundPlaying&&(0==m_soundPlaying.paused?m_soundPlaying.pause():m_soundPlaying.play())}function Play(a,c,b){"undefined"==typeof b&&null==b||PlaySound(b)}function PlayAction(){}function PauseVN(){}
function PauseVideo(a,c){}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}function PlayFromTo(a,c,b){m_soundPlaying=new buzz.sound(folder_Resource+"/"+a);m_soundPlaying.stop();m_soundPlaying.setTime(c);m_soundPlaying.play();m_soundPlaying.bind("timeupdate",function(){var a=m_soundPlaying.getTime();Number(a)>=Number(b)&&(m_soundPlaying.unbind("timeupdate"),m_soundPlaying.stop())})}
function PlaySound(a,c,b){m_soundPlaying=null;"undefined"!=typeof b?(m_soundPlaying=new buzz.sound(b),m_soundPlaying.load=!0,m_soundPlaying.play()):"undefined"!=typeof c?(a=new buzz.sound(folder_Resource+"/"+a),0===c?a.unloop():a.loop(),a.load=!0,a.play()):null==m_soundPlaying&&(m_soundPlaying=new buzz.sound(folder_Resource+"/"+a),m_soundPlaying.load=!0,m_soundPlaying.play())}
function PlayListSound(a){for(var c=1,b=[],e=0;e<arguments.length-1;e++)b[e]=new buzz.sound(folder_Resource+"/"+arguments[e+1]),b[e].load(),e<arguments.length-2?b[e].bind("ended",function(a){m_soundPlaying=b[c];b[c].play();c++}):e==arguments.length-2&&b[e].bind("ended",function(b){eval(a)});m_soundPlaying=b[0];b[0].play()}
function PlayWave(a,c,b){null!=m_soundPlaying&&m_soundPlaying.stop();m_soundPlaying=new buzz.sound(folder_Resource+"/"+b);m_soundPlaying.play();m_soundPlaying.bind("canplaythrough",function(a){_global_lenSound=1E3*a.currentTarget.duration})}
function PrevPage(){if(!(0>=g_iCurrentPage)){var a=stage.children;curentPage.hide();curentPage.draw();--g_iCurrentPage;curentPage=a[g_iCurrentPage];m_pgObjCaller=null;a=curentPage.getInitConfig();a.callback&&eval(a.callback);curentPage.show();curentPage.draw()}}function Print(a){curentPage.toImage({callback:function(a){window.open(a.src)},mimeType:"image/jpeg",quality:.5})}function PrintHTML(a,c){curentPage.toImage({callback:function(a){window.open(a.src)},mimeType:"image/jpeg",quality:.5})}
function Random(a){return Math.floor(Math.random()*a)}function RecordSound(a,c){}function PosInObj(a){a=FindShape("",a);if(null==a)return!1;var c=stage.getMousePosition();return"undefined"!=typeof c?a.intersects(c):!1}function PointInObj(a,c){return c.intersects(a)}function RectInRect(a,c,b){c=FindShape(a,c);if(null==c)return!1;a=FindShape(a,b);if(null==a)return!1;b=stage.getMousePosition();if("undefined"!=typeof b)return PointInObj(b,c)&&PointInObj(b,a)?!0:!1}
function RotateObj(a,c,b,e,f){a=FindShape(a,c);null!=a&&(c=a.getWidth()/2,e=a.getHeight()/2,f=a.getOffset(),0==f.x&&0==f.y&&(a.move(c,e),a.setOffset(c,e)),a.setRotationDeg(b),curentPage.draw())}function Offset(a,c,b,e){var f=FindShape(a,c);if(null!=f){if(3>arguments.length)return 0;f.setOffset(b,e)}}function Rotating(a,c,b,e){a=FindShape(a,c);null!=a&&(a.setOpacity(b/255),curentPage.draw())}function SetSelWord(a,c){}function Save(){}
function SaveObject(a,c){getImageData(a,c);if(null!==imageData){var b=FindShape(a,c);x_obj=parseInt(b.getX()*m_dZoomScale);y_obj=parseInt(b.getY()*m_dZoomScale);width=parseInt(b.getWidth()*m_dZoomScale);height=parseInt(b.getHeight()*m_dZoomScale);var e=document.createElement("canvas");e.id="canvas";e.width=width;e.height=height;e.getContext("2d").putImageData(imageData,0,0,0,0,width,height);var e=e.toDataURL(),f=new Image;f.crossOrigin="anonymous";f.onload=function(){b.setFill({image:f,offset:[0,
0],repeat:"stress"})};f.src=e}}function writeConsole(a){top.consoleRef=window.open("","myconsole","width=640,height=480,menubar=0,toolbar=1,status=0,scrollbars=1,resizable=1");top.consoleRef.document.writeln('<html><head><title>Lac Viet</title></head><body bgcolor=white onLoad="self.focus()"><img alt="" src="'+a+'" /></body></html>');top.consoleRef.document.close()}
function SaveID(a,c,b){var e=FindShape(a,c);x_obj=parseInt(e.getX()*m_dZoomScale);y_obj=parseInt(e.getY()*m_dZoomScale);width=parseInt(e.getWidth()*m_dZoomScale);height=parseInt(e.getHeight()*m_dZoomScale);a=document.createElement("canvas");a.id="canvas";a.width=width;a.height=height;c=a.getContext("2d");imageData=e.getContext().getImageData(x_obj,y_obj,width,height);c.putImageData(imageData,0,0,0,0,width,height);a=a.toDataURL();var f=new Image;f.crossOrigin="anonymous";f.onload=function(){e.setFill({image:f,
offset:[0,0],repeat:"stress"})};f.src=a;writeConsole(a)}function SavePage2File(a,c,b){curentPage.toImage({callback:function(a){writeConsole(a.src)},mimeType:"image/jpeg",quality:.5})}function ScaleObj(a,c,b){a=FindShape(a,c);null!=a&&a.setScale(b,b)}function Scaling(a,c,b){a=FindShape(a,c);null!=a&&a.setOpacity(b/255)}function SelectText(a,c,b,e,f,k,g){}function SentScript(a){}function ResumeVN(){}function ResumeEN(){}function SentScriptTo(a,c,b){}
function SetBorder(a,c,b,e,f){a=FindShape(a,c);if(null!=a){if("undefined"===typeof b)return a.getStrokeWidth();0===e?a.setStrokeWidth(1E-4):a.setStrokeWidth(e);a.setStroke(b)}}function GetBorderWidth(a,c){var b=FindShape(a,c);if(null!=b)return b.getStrokeWidth()}
function SetColor(a,c,b,e,f,k){var g=FindShape(a,c);if(null!=g)if(2==arguments.length){var m=g.getInitConfig();g.setFill(m.fill)}else if("undefined"!=typeof k||null!=k){k=k.replace(/[*:?<>"|\/]/ig,"");var l=new Image;l.crossOrigin="anonymous";l.onload=function(){g.setFill({image:l,offset:[0,0],repeat:"stress"});stage.draw()};l.crossOrigin="anonymous";l.onerror=function(){this.src=folder_Resource+"\\"+k+".JPG";this.onerror=function(){this.src=folder_Resource+"\\"+k+".GIF";this.onerror=function(){this.src=
folder_Resource+"\\"+k+".BMP";this.onerror=function(){Message("Object "+g.getName()+" kh\u00f4ng tim th\u1ea5y id rsc: "+k)}}}};l.src=folder_Resource+"\\"+k+".PNG"}else"undefined"!=typeof b&&"undefined"==typeof f&&"undefined"==typeof e?g.setFill(b):"-1"==b&&"-1"==f&&"-1"==e?(m=g.getInitConfig(),g.setFill(m.fill)):null!=b&&null!=f&&null!=e&&g.setFill(("rgba("+b+","+e+","+f+",1)").toString())}
function SetColorEx(a,c,b,e,f,k){var g=FindShape(a,c);if(null!=g)if(null!=e){e=e.toString().replace(/[*:?<>"|\/]/ig,"");var m=new Image;m.crossOrigin="anonymous";m.onload=function(){g.setFill({image:m,offset:[0,0],repeat:"stress"});curentPage.draw()};m.onerror=function(){this.src=folder_Resource+"\\"+e+".JPG";this.onerror=function(){this.src=folder_Resource+"\\"+e+".GIF";this.onerror=function(){this.src=folder_Resource+"\\"+e+".BMP";this.onerror=function(){Message("Kh\u00f4ng tim th\u1ea5y id rsc: "+
e)}}}};m.src=folder_Resource+"\\"+e+".PNG"}else null!=b&&("-1"==b?g.setFill("rgba(0, 0, 0, 0)"):g.setFill(b))}function GetTableValue(a,c,b,e,f){}function SetColorPaint(a,c){}function SetColorText(a,c,b,e,f,k,g,m,l){}var myVarTimerPage=null;function SetTimerPage(a){myVarTimerPage&&clearInterval(myVarTimerPage);var c=curentPage.getName()+"_OnTimer";"function"===typeof window[c]&&(myVarTimerPage=setInterval(function(){window[c]()},a))}function SetMidiVolume(a){m_soundPlaying.setVolume(a)}
function SetCursor(a,c,b){c=FindShape(a,c);null!=c&&(c.on("mouseover",function(){if(-1<"default crosshair e-resize help move n-resize ne-resize nw-resize pointer progress s-resize se-resize sw-resize text w-resize wait".indexOf(b))document.body.style.cursor=b;else{var a="url('{0}/{1}.ICO'), auto".format(folder_Resource,b);document.body.style.cursor=a}}),c.on("mouseout",function(){document.body.style.cursor="default"}),FindPage(a).draw())}function SetDigitEditText(a,c,b){}
function SetFileMovie(a,c,b){}
function SetRsc(a,c,b){var e=document.getElementById(c);if(null!=e)a=e.cloneNode(!0),a.setAttribute("src",folder_Resource+"\\"+b+".SWF"),e.parentNode.replaceChild(a,e);else{var f=FindShape(a,c);if(null!=f)if("undefined"!=typeof b||null!=b){if(f.setRsc(b),b=b.toString(),""!==b){b=b.replace(/[*:?<>"|\/]/ig,"");var k=new Image;k.crossOrigin="anonymous";k.onload=function(){f.setFill({image:k,offset:[0,0]});stage.draw()};k.onerror=function(){this.src=folder_Resource+"\\"+b+".JPG";this.onerror=function(){this.src=
folder_Resource+"\\"+b+".GIF";this.onerror=function(){Message("Kh\u00f4ng tim th\u1ea5y id rsc: "+b)}}};k.src=folder_Resource+"\\"+b+".PNG"}}else e=f.getInitConfig(),f.setFill(e.fill)}}function SetText(a,c,b){a=FindShape(a,c);null!=a&&("undefined"===typeof b?(b=a.getInitConfig(),a.setText(b.text)):a.setText(b.toString()))}
function SetMoveView(a,c,b){var e=null,e=""===c?m_pgObjCaller:FindShape(a,c);if(null!=e)if(0==b)e.setDraggable(!1);else if(e.setDraggable(!0),e.off("mouseup"),2==b)e.setDraggable(!0),e.setDragBoundFunc(function(a){return{x:a.x,y:this.getAbsolutePosition().y}});else if(3==b)e.setDraggable(!0),e.setDragBoundFunc(function(a){return{x:this.getAbsolutePosition().x,y:a.y}});else if(isNaN(b)){var f=FindShape(a,b);if(null==f)return null;e.setDragBoundFunc(function(a){var b=a.x<f.getX()*m_dZoomScale?f.getX()*
m_dZoomScale:a.x,c=a.y<f.getY()*m_dZoomScale?f.getY()*m_dZoomScale:a.y,b=a.x+this.getWidth()*m_dZoomScale>(f.getX()+f.getWidth())*m_dZoomScale?(f.getX()+f.getWidth()-this.getWidth())*m_dZoomScale:b,c=a.y+this.getHeight()*m_dZoomScale>(f.getY()+f.getHeight())*m_dZoomScale?(f.getY()+f.getHeight()-this.getHeight())*m_dZoomScale:c;return{x:b,y:c}})}}
function SetRectMove(a,c,b,e){c=FindShape(a,c);var f=FindShape(a,b);if(null==c||null==f)return null;c.setDragBoundFunc(function(a){var b=a.x<f.getX()*m_dZoomScale?f.getX()*m_dZoomScale:a.x,c=a.y<f.getY()*m_dZoomScale?f.getY()*m_dZoomScale:a.y,b=a.x+this.getWidth()*m_dZoomScale>(f.getX()+f.getWidth())*m_dZoomScale?(f.getX()+f.getWidth()-this.getWidth())*m_dZoomScale:b,c=a.y+this.getHeight()*m_dZoomScale>(f.getY()+f.getHeight())*m_dZoomScale?(f.getY()+f.getHeight()-this.getHeight())*m_dZoomScale:c;
return{x:b,y:c}})}function SpeakEN(a,c,b){responsiveVoice.isPlaying()&&responsiveVoice.cancel();"undefined"===typeof b&&(b=FindShape(a,c).getText());responsiveVoice.speak('"'+b.toString()+'"',"US English Female",{pitch:1,rate:.8})}function Stop(a,c,b){}
function SpeakVN(a,c,b,e,f){responsiveVoice.isPlaying()&&responsiveVoice.cancel();f=1;"undefined"!=typeof e&&(f=e);"undefined"===typeof b||""==b?(b=FindShape(a,c).getText(),responsiveVoice.speak(b.toString(),"Vietnamese Male",{pitch:f,rate:.8})):responsiveVoice.speak('"'+b.toString()+'"',"Vietnamese Male",{pitch:f,rate:.8})}function SetSpeaker(a){responsiveVoice.setDefaultVoice("US English Female")}
function animateMoveTo(a,c,b,e,f,k,g){if(b.animate){var m=(new Date).getTime(),l=m-a,u=l*k,n=l*g,q=c.getX(),x=c.getY();b.countTime+=l;b.countTime>=b.sumTime&&(q=e,x=f);if(q!=e||x!=f){var v,w;q<e?(v=q+u,v>e&&(v=e)):q>e&&(v=q-u,v<e&&(v=e));x<f?(w=x+n,w>f&&(w=f)):x>f&&(w=x-n,w<f&&(w=f));c.setX(v);c.setY(w)}else b.animate=!1,c.setX(e),c.setY(f);a=m;curentPage.draw();requestAnimFrame(function(){animateMoveTo(a,c,b,e,f,k,g)})}else EvenStopMove(c)}
function MoveObject(a,c,b,e){if(null==e)a.setPosition(c,b),curentPage.draw();else{var f={animate:!0,countTime:0,sumTime:e},k=(new Date).getTime();a.getX()==c&&c++;a.getY()==b&&b++;var g=Math.abs(a.getX()-c)/e;e=Math.abs(a.getY()-b)/e;animateMoveTo(k,a,f,c,b,g,e)}}function SetMute(a){m_soundPlaying.mute()}function StopSound(){m_soundPlaying.stop()}function SetVisible(a,c,b){var e=null,e=""===c?m_pgObjCaller:FindShape(a,c);null!=e&&(e.setVisible(b),curentPage.draw())}
function hexToRgb(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16),toString:function(){var a=[];a.push(this.r);a.push(this.g);a.push(this.b);a.push(1);return"rgba("+a.join(",")+")"}}:null}
function SetFontColor(a,c,b,e){"undefined"!=typeof b&&"undefined"!=typeof c&&(a=FindShape(a,c),null!=a&&("-1"==b?(b=a.getInitConfig(),a.setTextFill(b.textFill)):(isNaN(b)||(b=parseInt(b)),b=b.toString(16),b="FF0000".substr(0,6-b.length)+b,b=hexToRgb(b).toString(),a.setTextFill(b))))}function SetFontSize(a,c,b,e){a=FindShape(a,c);null!=a&&(a.setFontSize(80*parseInt(b)/100),"undefined"!=typeof e&&InvalidateObj("",""))}
function getMousePoint(a){var c={x:0,y:0};"undefined"!=typeof window.pageYOffset?(c.x=window.pageXOffset,c.y=window.pageYOffset):"undefined"!=typeof document.compatMode&&"BackCompat"!=document.compatMode?(c.x=document.documentElement.scrollLeft,c.y=document.documentElement.scrollTop):"undefined"!=typeof document.body&&(c.x=document.body.scrollLeft,c.y=document.body.scrollTop);c.x+=a.clientX;c.y+=a.clientY;return c}
function SetPaint(a,c,b){var e=FindShape(a,c);if(null!=e){if("undefined"==typeof b)return e.getPaint();e.setPaint(b);1==b&&(e.on("mouseup touchend dragend",function(a){m_pgObjCaller=this;PaintUpObj(stage.getMousePosition().x,stage.getMousePosition().y,e.getName())}),e.on("mousedown touchstart",function(a){m_pgObjCaller=this;PaintDownObj(stage.getMousePosition().x,stage.getMousePosition().y,e.getName(),40)}),e.on("mousemove touchmove dragmove",function(a){m_pgObjCaller=this;PaintMoveObj(stage.getMousePosition().x,
stage.getMousePosition().y,e.getName())}))}}function SetFontStyle(a,c,b,e){a=FindShape(a,c);null!=a&&(b=b.toUpperCase(),a.setFontStyle("R"==b||""==b?"normal":"B"==b?"bold":"I"==b?"italic":"BI"==b?"Bold Italic":"U"==b?"Underline":"S"==b?"Strikeout":"normal;"),"undefined"!=typeof e&&InvalidateObj("",""))}
function SetShowObject(a,c,b){var e=null,e=""===c?m_pgObjCaller:FindShape(a,c);if(null!=e){if(1==b||1==b)e.show();else for(e.hide();"Layer"!=curentPage.nodeType;)curentPage=curentPage.parent;curentPage.draw()}}var myArray=[];function SetVar(a,c){myArray[a]=c}function SetRect(a,c,b,e,f,k,g){a=FindShape(a,c);null!=a&&(-1!=b&&a.setX(b),-1!=e&&a.setY(e),-1!=f&&a.setWidth(f),-1!=k&&a.setHeight(k),"undefined"!=typeof g&&curentPage.draw())}
function LineHeight(a,c,b){var e=FindShape(a,c);if(null!=e){if(3>arguments.length)return e.getLineHeight(b);e.setLineHeight(b)}}function SetScriptPage(a,c,b){}function UTF8Upper(a){return String(a).toUpperCase()}function UTF8Lower(a){return String(a).toLowerCase()}function toLowerCase(a){return String(a).toLowerCase()}function toUpperCase(a){return String(a).toUpperCase()}
function getColorValues(a){var c={red:null,green:null,blue:null,alpha:1};"string"==typeof a&&(0===a.indexOf("#")?(a=a.substr(1),c=3==a.length?{red:parseInt(a[0]+a[0],16)||0,green:parseInt(a[1]+a[1],16)||0,blue:parseInt(a[2]+a[2],16)||0,alpha:1}:{red:parseInt(a.substr(0,2),16)||0,green:parseInt(a.substr(2,2),16)||0,blue:parseInt(a.substr(4,2),16)||0,alpha:1}):0===a.indexOf("rgb(")?(c=a.indexOf(","),c={red:parseInt(a.substr(4,c)),green:parseInt(a.substr(c+1,a.indexOf(",",c))),blue:parseInt(a.substr(a.indexOf(",",
c+1)+1,a.indexOf(")"))),alpha:1}):0===a.indexOf("rgba(")?(c=a.indexOf(","),repars=a.indexOf(",",c+1),c={red:parseInt(a.substr(5,c)),green:parseInt(a.substr(c+1,repars)),blue:parseInt(a.substr(a.indexOf(",",c+1)+1,a.indexOf(",",repars))),alpha:parseFloat(a.substr(a.indexOf(",",repars+1)+1,a.indexOf(")")))}):void 0!=stdCol[a]&&(c=getColorValues(stdCol[a])));return c="rgba("+c.red+","+c.green+","+c.blue+","+c.alpha+")"}function ShowColor(a,c){FindShape(a,c)}function ShowFont(a,c){FindShape(a,c)}
function SetFlash(){}function StopAction(){}function StopRecord(a,c){}function Transparent(a,c,b,e){a=FindShape(a,c);if(null!=a){if("undefined"==typeof b)return a.getOpacity();a.setOpacity(b/255)}}function UTF8ToVietNam(a){return a}function SetFocusObj(a){m_pgObjCaller=FindShape("",a)}function abs(a){return Math.abs(a)}function pow(a,c){return Math.pow(a,c)}String.prototype.replaceAll=function(a,c){for(var b=this,e=b.indexOf(a);-1!=e;)b=b.replace(a,c),e=b.indexOf(a);return b};
function replaceStr(a,c,b,e,f){if("undefined"==typeof a||null==a)return"";if("undefined"!=typeof e||null!=e){if("undefined"==typeof f||null==f)f=1;var k=a=a.toString();a=a.substring(e);e=a.indexOf(c);for(var g=0;-1!=e&&g<f;)k=a.replace(c,b),e=k.indexOf(c),g++;return k}return a.toString().replaceAll(c,b)}function rightStr(a,c){var b;if(0>=c)return"";c>String(a).length?b=a:(b=String(a).length,b=String(a).substring(b,b-c));return""==b||isNaN(b)?b:parseInt(b)}
function leftStr(a,c){var b="";if(0>=c)return b;b=c>String(a).length?a:String(a).substring(0,c);return""==b||isNaN(b)?b:parseInt(b)}function formatNumber(a,c){return a.toFixed(c)}function min(a,c){return Math.min(a,c)}function max(a,c){return Math.max(a,c)}function ceil(a){return Math.ceil(a)}function floor(a){return Math.floor(a)}function sin(a){return Math.sin(a)}function round(a){return Math.round(a)}function sqrt(a){return Math.sqrt(a)}
function wordCountStr(a){a=a.replace(/(^\s*)|(\s*$)/gi,"");a=a.replace(/[ ]{2,}/gi," ");a=a.replace(/\n /,"\n");a=a.split(" ");return a.length}function ltrimStr(a,c){var b=" ";"undefined"!=typeof c&&(b=c);for(var e=0;e<a.length&&a[e]==b;)e++;return a.substring(e,a.length)}function rtrimStr(a,c){for(var b=a.length-1;0<b&&a[b]==c;)--b;return a.substring(0,b+1)}function trimStr(a,c){return"undefined"==typeof c||null==c?a.toString().trim():rtrimStr(ltrimStr(a,c),c)}
function LoaiBoDau(a){a=a.replace(/\u00e0|\u00e1|\u1ea1|\u1ea3|\u00e3/g,"a");a=a.replace(/\u1ea7|\u1ea5|\u1ead|\u1ea9|\u1eab/g,"\u00e2");a=a.replace(/\u1eb1|\u1eaf|\u1eb7|\u1eb3|\u1eb5/g,"\u0103");a=a.replace(/\u00e8|\u00e9|\u1eb9|\u1ebb|\u1ebd/g,"e");a=a.replace(/\u1ec1|\u1ebf|\u1ec7|\u1ec3|\u1ec5/g,"\u00ea");a=a.replace(/\u00f9|\u00fa|\u1ee5|\u1ee7|\u0169/g,"u");a=a.replace(/\u1eeb|\u1ee9|\u1ef1|\u1eed|\u1eef/g,"\u01b0");a=a.replace(/\u1ef3|\u00fd|\u1ef5|\u1ef7|\u1ef9/g,"y");a=a.replace(/\u00ec|\u00ed|\u1ecb|\u1ec9|\u0129/g,
"i");a=a.replace(/\u00f2|\u00f3|\u1ecd|\u1ecf|\u00f5/g,"o");a=a.replace(/\u1ed3|\u1ed1|\u1ed9|\u1ed5|\u1ed7/g,"\u00f4");return a=a.replace(/\u1edd|\u1edb|\u1ee3|\u1edf|\u1ee1/g,"\u01a1")}function wordsStr(a,c,b){a=a.split(/[, ]+/);a.length<b&&(b=a.length);--c;for(var e="",f=0;f<b;f++)e=e+a[c]+" ",c+=1;e=e.trim();return isNaN(e)?e:parseInt(e)}function indexOf(a,c,b,e){return"undefined"!=typeof e&&0<e?a.toLowerCase().indexOf(c.toLowerCase(),b):a.indexOf(c,b)}
function subString(a,c,b,e){e="";a=a.toString();"undefined"==typeof b&&a.substr(c);e=a.substr(c,b);if(""==e||isNaN(e))return e;a=parseInt(e);return isNaN(a)?e:a}function length(a){return String(a).length}function Length(a){return length(a)}function setTimeoutFunction(a,c){setTimeout(a,c)}function ShapeType(a,c,b){a=FindShape(a,c);if(null!=a){if("undefined"===typeof b)return a.attrs.shapeType;a.attrs.shapeType=b}}
function AddObjToCurentPage(a){for(var c=null,b=stage.children,e=0;e<b.length;e++){var f=FindShape(b[e].getName(),a);if(f){c=f.clone();f.remove();break}}null!=c&&m_pgObjCaller.parent.add(c)}function StringtoNumber(a,c){for(var b=0,e="",f=!0;b<a.length&&f;)isNaN(a[b])?""!=e&&(f=!1):e+=a[b],b++;return Number(e)}function Hour(){d=new Date;return d.getHours()}function Mimute(){d=new Date;return d.getMinutes()}function Second(){d=new Date;return d.getSeconds()}
function Day(){d=new Date;return d.getDate()}function Month(){d=new Date;return d.getMonth()}function Year(){d=new Date;return d.getFullYear()};
